### ISSUE TITLE
Freezes on first frame on iOS 6

### ISSUE THREAD

**Issue by alastairstuart** [mateagar/Motion-JPEG-Image-View-for-iOS#1]
Building against 5.1, runs fine in the 5.1 simulator but freezes on the first frame on an iOS 6 device.

**Comment by mateagar** [comment]
I'm running it on my iPhone 5 without issue.

Matt

On Oct 2, 2012, at 9:06 AM, alastairstuart notifications@github.com wrote:

Building against 5.1, runs fine in the 5.1 simulator but freezes on the first frame on an iOS 6 device.

**Comment by alastairstuart** [comment]
With the included test mJPEG URL it works fine, however my GrandStream GXV3615WP_HD is exhibiting this issue. I'll try and dig farther.
