### ISSUE TITLE
Crash if this is constructed in Interface Builder

### ISSUE THREAD

**Issue by torinnguyen** [mateagar/Motion-JPEG-Image-View-for-iOS#3]
_endMarkerData is only initialized in initWithFrame initializer function

Therefore, it will crash later in - (void)connection:(NSURLConnection *)connection didReceiveData:(NSData *)data 
where you pass in rangeOfData with a nil parameter

Crash log:
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSConcreteMutableData rangeOfData:options:range:]: nil data argument'
**\* First throw call stack:

To support Interface Builder, duplicate the initializer code into
-(id)initWithCoder:(NSCoder*)coder

**Comment by mateagar** [comment]
You are welcome to make changes to support Interface Builder if you like. I don't use Interface Builder personally, so I haven't tested with it.

**Comment by kristopherjohnson** [comment]
I have submitted a pull request with a fix. You need to add an override of -awakeWithNib that initializes _endMarkerData the same way that -initWithFrame does.
